model:
  name: EleutherAI/pythia-410m
  revision: "9879c9b5f8bea9051dcb0e68dff21493d67e9d4f"
  trust_remote_code: false

  lora:
    enabled: true
    rank: 8
    alpha: 16
    dropout: 0.05
    target_modules:
      - query_key_value
    bias: none
    task_type: CAUSAL_LM
